[package]
name = "protostar"
version = "0.4.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.3", features = ["derive"] }
color-eyre = "0.6.2"
directories = "4.0.1"
dirs = "4.0.0"
ez-pixmap = "0.2.2"
glam = { version = "0.22.0", features = ["mint"] }
image = "0.24.5"
lazy_static = "1.4.0"
linicon = "2.3.0"
manifest-dir-macros = "0.1.16"
mint = "0.5.9"
nix = "0.26.1"
resvg = "0.29.0"
rustc-hash = "1.1.0"
stardust-xr-fusion = "0.38.0"
stardust-xr-molecules = "0.21.0"
tokio = { version = "1.24.1", features = ["full"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tween = "2.0.0"
ustr = "0.9.0"
walkdir = "2.3.2"

[dev-dependencies]
tempdir = "0.3.7"